import type {
  AccountSnapshot,
  ApprovalRequest,
  ConversationItem,
  RateLimitSnapshot,
  RequestUserInputRequest,
  ThreadListSortKey,
  ThreadSummary,
  ThreadTokenUsage,
  TurnPlan,
<<<<<<< HEAD
} from "../../../types";
import {
  normalizeItem,
  prepareThreadItems,
  prepareThreadItemsIncremental,
  upsertItem,
} from "../../../utils/threadItems";

const MAX_THREAD_NAME_LENGTH = 38;

function formatThreadName(text: string) {
  const trimmed = text.trim();
  if (!trimmed) {
    return null;
  }
  return trimmed.length > MAX_THREAD_NAME_LENGTH
    ? `${trimmed.slice(0, MAX_THREAD_NAME_LENGTH)}…`
    : trimmed;
}

function looksAutoGeneratedThreadName(name: string) {
  return name === "New Agent" || name.startsWith("Agent ") || /^[a-f0-9]{4,8}$/i.test(name);
}

function extractRenameText(text: string) {
  if (!text) {
    return "";
  }
  const withoutImages = text.replace(/\[image(?: x\d+)?\]/gi, " ");
  const withoutSkills = withoutImages.replace(/(^|\s)\$[A-Za-z0-9_-]+(?=\s|$)/g, " ");
  return withoutSkills.replace(/\s+/g, " ").trim();
}

function getAssistantTextForRename(
  items: ConversationItem[],
  itemId?: string,
): string {
  if (itemId) {
    const match = items.find(
      (item) =>
        item.kind === "message" &&
        item.role === "assistant" &&
        item.id === itemId,
    );
    if (match && match.kind === "message") {
      return match.text;
    }
  }
  for (let index = items.length - 1; index >= 0; index -= 1) {
    const item = items[index];
    if (item.kind === "message" && item.role === "assistant") {
      return item.text;
    }
  }
  return "";
}

function maybeRenameThreadFromAgent({
  workspaceId,
  threadId,
  items,
  itemId,
  hasCustomName,
  threadsByWorkspace,
}: {
  workspaceId: string;
  threadId: string;
  items: ConversationItem[];
  itemId?: string;
  hasCustomName: boolean;
  threadsByWorkspace: Record<string, ThreadSummary[]>;
}) {
  const threads = threadsByWorkspace[workspaceId] ?? [];
  if (!threads.length) {
    return threadsByWorkspace;
  }
  const hasUserMessage = items.some(
    (item) => item.kind === "message" && item.role === "user",
  );
  if (hasUserMessage) {
    return threadsByWorkspace;
  }
  if (hasCustomName) {
    return threadsByWorkspace;
  }
  const nextName = formatThreadName(getAssistantTextForRename(items, itemId));
  if (!nextName) {
    return threadsByWorkspace;
  }
  let didChange = false;
  const nextThreads = threads.map((thread) => {
    if (
      thread.id !== threadId ||
      thread.name === nextName ||
      !looksAutoGeneratedThreadName(thread.name)
    ) {
      return thread;
    }
    didChange = true;
    return { ...thread, name: nextName };
  });
  return didChange
    ? { ...threadsByWorkspace, [workspaceId]: nextThreads }
    : threadsByWorkspace;
}
=======
} from "@/types";
import { CHAT_SCROLLBACK_DEFAULT } from "@utils/chatScrollback";
import { reduceThreadItems } from "./threadReducer/threadItemsSlice";
import { reduceThreadLifecycle } from "./threadReducer/threadLifecycleSlice";
import { reduceThreadConfig } from "./threadReducer/threadConfigSlice";
import { reduceThreadQueue } from "./threadReducer/threadQueueSlice";
import { reduceThreadSnapshots } from "./threadReducer/threadSnapshotSlice";
>>>>>>> origin/main

type ThreadActivityStatus = {
  isProcessing: boolean;
  hasUnread: boolean;
  isReviewing: boolean;
  processingStartedAt: number | null;
  lastDurationMs: number | null;
  lastActivityAt?: number | null;
  lastErrorAt?: number | null;
  lastErrorMessage?: string | null;
};

type ThreadTurnRuntimeMeta = {
  threadId: string;
  turnId: string;
  model: string | null;
  contextWindow: number | null;
};

export type ThreadState = {
  activeThreadIdByWorkspace: Record<string, string | null>;
  itemsByThread: Record<string, ConversationItem[]>;
  threadsByWorkspace: Record<string, ThreadSummary[]>;
  hiddenThreadIdsByWorkspace: Record<string, Record<string, true>>;
  threadParentById: Record<string, string>;
  threadStatusById: Record<string, ThreadActivityStatus>;
  threadResumeLoadingById: Record<string, boolean>;
  threadListLoadingByWorkspace: Record<string, boolean>;
  threadListPagingByWorkspace: Record<string, boolean>;
  threadListCursorByWorkspace: Record<string, string | null>;
  threadSortKeyByWorkspace: Record<string, ThreadListSortKey>;
  activeTurnIdByThread: Record<string, string | null>;
  turnDiffByThread: Record<string, string>;
  approvals: ApprovalRequest[];
  userInputRequests: RequestUserInputRequest[];
  tokenUsageByThread: Record<string, ThreadTokenUsage>;
  turnMetaByThread: Record<string, ThreadTurnRuntimeMeta | null>;
  turnMetaByTurnId: Record<string, ThreadTurnRuntimeMeta>;
  rateLimitsByWorkspace: Record<string, RateLimitSnapshot | null>;
  accountByWorkspace: Record<string, AccountSnapshot | null>;
  planByThread: Record<string, TurnPlan | null>;
  lastAgentMessageByThread: Record<string, { text: string; timestamp: number }>;
};

export type ThreadAction =
  | { type: "setActiveThreadId"; workspaceId: string; threadId: string | null }
  | { type: "ensureThread"; workspaceId: string; threadId: string }
  | { type: "hideThread"; workspaceId: string; threadId: string }
  | { type: "removeThread"; workspaceId: string; threadId: string }
  | { type: "setThreadParent"; threadId: string; parentId: string }
  | {
      type: "markProcessing";
      threadId: string;
      isProcessing: boolean;
      timestamp: number;
    }
  | { type: "markReviewing"; threadId: string; isReviewing: boolean }
  | { type: "markUnread"; threadId: string; hasUnread: boolean }
  | {
      type: "markThreadError";
      threadId: string;
      timestamp: number;
      message: string;
    }
  | { type: "addAssistantMessage"; threadId: string; text: string }
  | { type: "setThreadName"; workspaceId: string; threadId: string; name: string }
  | {
      type: "setThreadTimestamp";
      workspaceId: string;
      threadId: string;
      timestamp: number;
    }
  | {
      type: "appendAgentDelta";
      workspaceId: string;
      threadId: string;
      itemId: string;
      delta: string;
      hasCustomName: boolean;
      turnId?: string | null;
    }
  | {
      type: "completeAgentMessage";
      workspaceId: string;
      threadId: string;
      itemId: string;
      text: string;
      hasCustomName: boolean;
      turnId?: string | null;
    }
  | {
      type: "upsertItem";
      workspaceId: string;
      threadId: string;
      item: ConversationItem;
      hasCustomName?: boolean;
    }
  | { type: "setThreadItems"; threadId: string; items: ConversationItem[] }
  | {
      type: "appendReasoningSummary";
      threadId: string;
      itemId: string;
      delta: string;
    }
  | {
      type: "appendReasoningSummaryBoundary";
      threadId: string;
      itemId: string;
    }
  | { type: "appendReasoningContent"; threadId: string; itemId: string; delta: string }
  | { type: "appendPlanDelta"; threadId: string; itemId: string; delta: string }
  | { type: "appendToolOutput"; threadId: string; itemId: string; delta: string }
  | {
      type: "setThreads";
      workspaceId: string;
      threads: ThreadSummary[];
      sortKey: ThreadListSortKey;
    }
  | {
      type: "setThreadListLoading";
      workspaceId: string;
      isLoading: boolean;
    }
  | {
      type: "setThreadResumeLoading";
      threadId: string;
      isLoading: boolean;
    }
  | {
      type: "setThreadListPaging";
      workspaceId: string;
      isLoading: boolean;
    }
  | {
      type: "setThreadListCursor";
      workspaceId: string;
      cursor: string | null;
    }
  | { type: "addApproval"; approval: ApprovalRequest }
  | { type: "removeApproval"; requestId: number | string; workspaceId: string }
  | { type: "addUserInputRequest"; request: RequestUserInputRequest }
  | {
      type: "removeUserInputRequest";
      requestId: number | string;
      workspaceId: string;
    }
  | { type: "setThreadTokenUsage"; threadId: string; tokenUsage: ThreadTokenUsage }
  | {
      type: "setThreadTurnMeta";
      threadId: string;
      turnId: string;
      model: string | null;
    }
  | {
      type: "setThreadTurnContextWindow";
      threadId: string;
      turnId: string;
      contextWindow: number | null;
    }
  | {
      type: "setRateLimits";
      workspaceId: string;
      rateLimits: RateLimitSnapshot | null;
    }
  | {
      type: "setAccountInfo";
      workspaceId: string;
      account: AccountSnapshot | null;
    }
  | { type: "setActiveTurnId"; threadId: string; turnId: string | null }
  | { type: "setThreadTurnDiff"; threadId: string; diff: string }
  | { type: "setThreadPlan"; threadId: string; plan: TurnPlan | null }
  | { type: "clearThreadPlan"; threadId: string }
  | {
      type: "setLastAgentMessage";
      threadId: string;
      text: string;
      timestamp: number;
    }
  | {
      type: "setLastAgentMessagesBulk";
      updates: Array<{
        threadId: string;
        text: string;
        timestamp: number;
      }>;
    };

const emptyItems: Record<string, ConversationItem[]> = {};

export const initialState: ThreadState = {
  activeThreadIdByWorkspace: {},
  itemsByThread: emptyItems,
  threadsByWorkspace: {},
  hiddenThreadIdsByWorkspace: {},
  threadParentById: {},
  threadStatusById: {},
  threadResumeLoadingById: {},
  threadListLoadingByWorkspace: {},
  threadListPagingByWorkspace: {},
  threadListCursorByWorkspace: {},
  threadSortKeyByWorkspace: {},
  activeTurnIdByThread: {},
  turnDiffByThread: {},
  approvals: [],
  userInputRequests: [],
  tokenUsageByThread: {},
  turnMetaByThread: {},
  turnMetaByTurnId: {},
  rateLimitsByWorkspace: {},
  accountByWorkspace: {},
  planByThread: {},
  lastAgentMessageByThread: {},
};

type ThreadSliceReducer = (state: ThreadState, action: ThreadAction) => ThreadState;

<<<<<<< HEAD
function normalizeNonEmptyString(value: string | null | undefined) {
  if (typeof value !== "string") {
    return null;
  }
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : null;
}

function normalizeContextWindow(value: number | null | undefined) {
  if (typeof value !== "number" || !Number.isFinite(value) || value <= 0) {
    return null;
  }
  return value;
}

function resolveTurnMetaForMessage(
  state: ThreadState,
  threadId: string,
  turnId?: string | null,
): ThreadTurnRuntimeMeta | null {
  const normalizedTurnId = normalizeNonEmptyString(turnId);
  if (normalizedTurnId) {
    const byTurn = state.turnMetaByTurnId[normalizedTurnId] ?? null;
    if (byTurn && byTurn.threadId === threadId) {
      return byTurn;
    }
  }
  const byThread = state.turnMetaByThread[threadId] ?? null;
  if (!byThread) {
    return null;
  }
  if (normalizedTurnId && byThread.turnId !== normalizedTurnId) {
    return null;
  }
  return byThread;
}

function applyAssistantRuntimeMeta(
  item: Extract<ConversationItem, { kind: "message" }>,
  meta: ThreadTurnRuntimeMeta | null,
  turnId?: string | null,
) {
  if (item.role !== "assistant") {
    return item;
  }
  const nextTurnId = normalizeNonEmptyString(turnId) ?? meta?.turnId ?? item.turnId ?? null;
  const nextModel = normalizeNonEmptyString(meta?.model) ?? item.model ?? null;
  const nextContextWindow = normalizeContextWindow(meta?.contextWindow) ?? item.contextWindow ?? null;
  return {
    ...item,
    turnId: nextTurnId,
    model: nextModel,
    contextWindow: nextContextWindow,
  };
}

function updateAssistantContextWindowForTurn(
  list: ConversationItem[],
  turnId: string,
  contextWindow: number | null,
) {
  const normalizedContextWindow = normalizeContextWindow(contextWindow);
  let didChange = false;
  const next = [...list];
  let hasExactTurnMatch = false;

  for (let index = 0; index < next.length; index += 1) {
    const item = next[index];
    if (item.kind !== "message" || item.role !== "assistant") {
      continue;
    }
    if (item.turnId !== turnId) {
      continue;
    }
    hasExactTurnMatch = true;
    if (item.contextWindow === normalizedContextWindow) {
      continue;
    }
    next[index] = {
      ...item,
      contextWindow: normalizedContextWindow,
    };
    didChange = true;
  }

  if (hasExactTurnMatch) {
    return didChange ? next : list;
  }

  for (let index = next.length - 1; index >= 0; index -= 1) {
    const item = next[index];
    if (item.kind !== "message" || item.role !== "assistant") {
      continue;
    }
    if (item.turnId && item.turnId !== turnId) {
      break;
    }
    if (item.contextWindow === normalizedContextWindow && item.turnId === turnId) {
      return list;
    }
    next[index] = {
      ...item,
      turnId,
      contextWindow: normalizedContextWindow,
    };
    return next;
  }

  return list;
}

function updateAssistantModelForTurn(
  list: ConversationItem[],
  turnId: string,
  model: string | null,
) {
  const normalizedModel = normalizeNonEmptyString(model);
  let didChange = false;
  const next = [...list];
  let hasExactTurnMatch = false;

  for (let index = 0; index < next.length; index += 1) {
    const item = next[index];
    if (item.kind !== "message" || item.role !== "assistant") {
      continue;
    }
    if (item.turnId !== turnId) {
      continue;
    }
    hasExactTurnMatch = true;
    if (item.model === normalizedModel) {
      continue;
    }
    next[index] = {
      ...item,
      model: normalizedModel,
    };
    didChange = true;
  }

  if (hasExactTurnMatch) {
    return didChange ? next : list;
  }

  for (let index = next.length - 1; index >= 0; index -= 1) {
    const item = next[index];
    if (item.kind !== "message" || item.role !== "assistant") {
      continue;
    }
    if (item.turnId && item.turnId !== turnId) {
      break;
    }
    if (item.turnId === turnId && item.model === normalizedModel) {
      return list;
    }
    next[index] = {
      ...item,
      turnId,
      model: normalizedModel,
    };
    return next;
  }

  return list;
}

function addSummaryBoundary(existing: string) {
  if (!existing) {
    return existing;
  }
  if (existing.endsWith("\n\n")) {
    return existing;
  }
  if (existing.endsWith("\n")) {
    return `${existing}\n`;
  }
  return `${existing}\n\n`;
}

function dropLatestLocalReviewStart(list: ConversationItem[]) {
  for (let index = list.length - 1; index >= 0; index -= 1) {
    const item = list[index];
    if (
      item.kind === "review" &&
      item.state === "started" &&
      item.id.startsWith("review-start-")
    ) {
      return [...list.slice(0, index), ...list.slice(index + 1)];
    }
  }
  return list;
}

function findMatchingReview(
  list: ConversationItem[],
  target: Extract<ConversationItem, { kind: "review" }>,
) {
  const normalizedText = target.text.trim();
  return list.find(
    (item) =>
      item.kind === "review" &&
      item.state === target.state &&
      item.text.trim() === normalizedText,
  );
}

function ensureUniqueReviewId(list: ConversationItem[], item: ConversationItem) {
  if (item.kind !== "review") {
    return item;
  }
  if (!list.some((entry) => entry.id === item.id)) {
    return item;
  }
  const existingIds = new Set(list.map((entry) => entry.id));
  let suffix = 1;
  let candidate = `${item.id}-${suffix}`;
  while (existingIds.has(candidate)) {
    suffix += 1;
    candidate = `${item.id}-${suffix}`;
  }
  return { ...item, id: candidate };
}

function isDuplicateReviewById(
  list: ConversationItem[],
  target: Extract<ConversationItem, { kind: "review" }>,
) {
  const normalizedText = target.text.trim();
  return list.some(
    (item) =>
      item.kind === "review" &&
      item.id === target.id &&
      item.state === target.state &&
      item.text.trim() === normalizedText,
  );
}

function prefersUpdatedSort(state: ThreadState, workspaceId: string) {
  return (state.threadSortKeyByWorkspace[workspaceId] ?? "updated_at") === "updated_at";
}

export function threadReducer(state: ThreadState, action: ThreadAction): ThreadState {
  switch (action.type) {
    case "setActiveThreadId":
      return {
        ...state,
        activeThreadIdByWorkspace: {
          ...state.activeThreadIdByWorkspace,
          [action.workspaceId]: action.threadId,
        },
        threadStatusById: action.threadId
          ? {
              ...state.threadStatusById,
              [action.threadId]: {
                isProcessing:
                  state.threadStatusById[action.threadId]?.isProcessing ?? false,
                hasUnread: false,
                isReviewing:
                  state.threadStatusById[action.threadId]?.isReviewing ?? false,
                processingStartedAt:
                  state.threadStatusById[action.threadId]?.processingStartedAt ??
                  null,
                lastDurationMs:
                  state.threadStatusById[action.threadId]?.lastDurationMs ?? null,
                lastActivityAt:
                  state.threadStatusById[action.threadId]?.lastActivityAt,
                lastErrorAt: state.threadStatusById[action.threadId]?.lastErrorAt,
                lastErrorMessage:
                  state.threadStatusById[action.threadId]?.lastErrorMessage,
              },
            }
          : state.threadStatusById,
      };
    case "ensureThread": {
      const hidden =
        state.hiddenThreadIdsByWorkspace[action.workspaceId]?.[action.threadId] ??
        false;
      if (hidden) {
        return state;
      }
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      if (list.some((thread) => thread.id === action.threadId)) {
        return state;
      }
      const thread: ThreadSummary = {
        id: action.threadId,
        name: "New Agent",
        updatedAt: 0,
      };
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: [thread, ...list],
        },
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            isProcessing: false,
            hasUnread: false,
            isReviewing: false,
            processingStartedAt: null,
            lastDurationMs: null,
            lastActivityAt: null,
            lastErrorAt: null,
            lastErrorMessage: null,
          },
        },
        activeThreadIdByWorkspace: {
          ...state.activeThreadIdByWorkspace,
          [action.workspaceId]:
            state.activeThreadIdByWorkspace[action.workspaceId] ?? action.threadId,
        },
      };
    }
    case "hideThread": {
      const hiddenForWorkspace =
        state.hiddenThreadIdsByWorkspace[action.workspaceId] ?? {};
      if (hiddenForWorkspace[action.threadId]) {
        return state;
      }

      const nextHiddenForWorkspace = {
        ...hiddenForWorkspace,
        [action.threadId]: true as const,
      };

      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      const filtered = list.filter((thread) => thread.id !== action.threadId);
      const nextActive =
        state.activeThreadIdByWorkspace[action.workspaceId] === action.threadId
          ? filtered[0]?.id ?? null
          : state.activeThreadIdByWorkspace[action.workspaceId] ?? null;

      return {
        ...state,
        hiddenThreadIdsByWorkspace: {
          ...state.hiddenThreadIdsByWorkspace,
          [action.workspaceId]: nextHiddenForWorkspace,
        },
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: filtered,
        },
        activeThreadIdByWorkspace: {
          ...state.activeThreadIdByWorkspace,
          [action.workspaceId]: nextActive,
        },
      };
    }
    case "removeThread": {
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      const filtered = list.filter((thread) => thread.id !== action.threadId);
      const nextActive =
        state.activeThreadIdByWorkspace[action.workspaceId] === action.threadId
          ? filtered[0]?.id ?? null
          : state.activeThreadIdByWorkspace[action.workspaceId] ?? null;
      const { [action.threadId]: _, ...restItems } = state.itemsByThread;
      const { [action.threadId]: __, ...restStatus } = state.threadStatusById;
      const { [action.threadId]: ___, ...restTurns } = state.activeTurnIdByThread;
      const { [action.threadId]: ____, ...restDiffs } = state.turnDiffByThread;
      const { [action.threadId]: _____, ...restPlans } = state.planByThread;
      const { [action.threadId]: ______, ...restParents } = state.threadParentById;
      const { [action.threadId]: _______, ...restTurnMetaByThread } = state.turnMetaByThread;
      const restTurnMetaByTurnId = Object.fromEntries(
        Object.entries(state.turnMetaByTurnId).filter(
          ([, meta]) => meta.threadId !== action.threadId,
        ),
      );
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: filtered,
        },
        itemsByThread: restItems,
        threadStatusById: restStatus,
        activeTurnIdByThread: restTurns,
        turnDiffByThread: restDiffs,
        planByThread: restPlans,
        threadParentById: restParents,
        turnMetaByThread: restTurnMetaByThread,
        turnMetaByTurnId: restTurnMetaByTurnId,
        activeThreadIdByWorkspace: {
          ...state.activeThreadIdByWorkspace,
          [action.workspaceId]: nextActive,
        },
      };
    }
    case "setThreadParent": {
      if (!action.parentId || action.parentId === action.threadId) {
        return state;
      }
      if (state.threadParentById[action.threadId] === action.parentId) {
        return state;
      }
      return {
        ...state,
        threadParentById: {
          ...state.threadParentById,
          [action.threadId]: action.parentId,
        },
      };
    }
    case "markProcessing": {
      const previous = state.threadStatusById[action.threadId];
      const wasProcessing = previous?.isProcessing ?? false;
      const startedAt = previous?.processingStartedAt ?? null;
      const lastDurationMs = previous?.lastDurationMs ?? null;
      const hasUnread = previous?.hasUnread ?? false;
      const isReviewing = previous?.isReviewing ?? false;
      const lastActivityAt = previous?.lastActivityAt;
      const lastErrorAt = previous?.lastErrorAt;
      const lastErrorMessage = previous?.lastErrorMessage;
      if (action.isProcessing) {
        const nextStartedAt =
          wasProcessing && startedAt ? startedAt : action.timestamp;
        const nextStatus: ThreadActivityStatus = {
          isProcessing: true,
          hasUnread,
          isReviewing,
          processingStartedAt: nextStartedAt,
          lastDurationMs,
          lastActivityAt:
            wasProcessing ? previous?.lastActivityAt : action.timestamp,
          lastErrorAt: null,
          lastErrorMessage: null,
        };
        if (
          previous &&
          previous.isProcessing === nextStatus.isProcessing &&
          previous.hasUnread === nextStatus.hasUnread &&
          previous.isReviewing === nextStatus.isReviewing &&
          previous.processingStartedAt === nextStatus.processingStartedAt &&
          previous.lastDurationMs === nextStatus.lastDurationMs &&
          previous.lastActivityAt === nextStatus.lastActivityAt &&
          previous.lastErrorAt === nextStatus.lastErrorAt &&
          previous.lastErrorMessage === nextStatus.lastErrorMessage
        ) {
          return state;
        }
        return {
          ...state,
          threadStatusById: {
            ...state.threadStatusById,
            [action.threadId]: nextStatus,
          },
        };
      }
      const nextDuration =
        wasProcessing && startedAt
          ? Math.max(0, action.timestamp - startedAt)
          : lastDurationMs ?? null;
      const nextStatus: ThreadActivityStatus = {
        isProcessing: false,
        hasUnread,
        isReviewing,
        processingStartedAt: null,
        lastDurationMs: nextDuration,
        lastActivityAt,
        lastErrorAt,
        lastErrorMessage,
      };
      if (
        previous &&
        previous.isProcessing === nextStatus.isProcessing &&
        previous.hasUnread === nextStatus.hasUnread &&
        previous.isReviewing === nextStatus.isReviewing &&
        previous.processingStartedAt === nextStatus.processingStartedAt &&
        previous.lastDurationMs === nextStatus.lastDurationMs &&
        previous.lastActivityAt === nextStatus.lastActivityAt &&
        previous.lastErrorAt === nextStatus.lastErrorAt &&
        previous.lastErrorMessage === nextStatus.lastErrorMessage
      ) {
        return state;
      }
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: nextStatus,
        },
      };
    }
    case "setActiveTurnId":
      return {
        ...state,
        activeTurnIdByThread: {
          ...state.activeTurnIdByThread,
          [action.threadId]: action.turnId,
        },
      };
    case "markReviewing": {
      const previous = state.threadStatusById[action.threadId];
      const nextStatus: ThreadActivityStatus = {
        isProcessing: previous?.isProcessing ?? false,
        hasUnread: previous?.hasUnread ?? false,
        isReviewing: action.isReviewing,
        processingStartedAt: previous?.processingStartedAt ?? null,
        lastDurationMs: previous?.lastDurationMs ?? null,
        lastActivityAt: previous?.lastActivityAt,
        lastErrorAt: previous?.lastErrorAt,
        lastErrorMessage: previous?.lastErrorMessage,
      };
      if (
        previous &&
        previous.isProcessing === nextStatus.isProcessing &&
        previous.hasUnread === nextStatus.hasUnread &&
        previous.isReviewing === nextStatus.isReviewing &&
        previous.processingStartedAt === nextStatus.processingStartedAt &&
        previous.lastDurationMs === nextStatus.lastDurationMs &&
        previous.lastActivityAt === nextStatus.lastActivityAt &&
        previous.lastErrorAt === nextStatus.lastErrorAt &&
        previous.lastErrorMessage === nextStatus.lastErrorMessage
      ) {
        return state;
      }
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: nextStatus,
        },
      };
    }
    case "markUnread": {
      const previous = state.threadStatusById[action.threadId];
      const nextStatus: ThreadActivityStatus = {
        isProcessing: previous?.isProcessing ?? false,
        hasUnread: action.hasUnread,
        isReviewing: previous?.isReviewing ?? false,
        processingStartedAt: previous?.processingStartedAt ?? null,
        lastDurationMs: previous?.lastDurationMs ?? null,
        lastActivityAt: previous?.lastActivityAt,
        lastErrorAt: previous?.lastErrorAt,
        lastErrorMessage: previous?.lastErrorMessage,
      };
      if (
        previous &&
        previous.isProcessing === nextStatus.isProcessing &&
        previous.hasUnread === nextStatus.hasUnread &&
        previous.isReviewing === nextStatus.isReviewing &&
        previous.processingStartedAt === nextStatus.processingStartedAt &&
        previous.lastDurationMs === nextStatus.lastDurationMs &&
        previous.lastActivityAt === nextStatus.lastActivityAt &&
        previous.lastErrorAt === nextStatus.lastErrorAt &&
        previous.lastErrorMessage === nextStatus.lastErrorMessage
      ) {
        return state;
      }
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: nextStatus,
        },
      };
    }
    case "markThreadError": {
      const previous = state.threadStatusById[action.threadId];
      const normalizedMessage = action.message.trim();
      const nextStatus: ThreadActivityStatus = {
        isProcessing: false,
        hasUnread: previous?.hasUnread ?? false,
        isReviewing: false,
        processingStartedAt: null,
        lastDurationMs: previous?.lastDurationMs ?? null,
        lastActivityAt: previous?.lastActivityAt,
        lastErrorAt: action.timestamp,
        lastErrorMessage: normalizedMessage || null,
      };
      if (
        previous &&
        previous.isProcessing === nextStatus.isProcessing &&
        previous.hasUnread === nextStatus.hasUnread &&
        previous.isReviewing === nextStatus.isReviewing &&
        previous.processingStartedAt === nextStatus.processingStartedAt &&
        previous.lastDurationMs === nextStatus.lastDurationMs &&
        previous.lastActivityAt === nextStatus.lastActivityAt &&
        previous.lastErrorAt === nextStatus.lastErrorAt &&
        previous.lastErrorMessage === nextStatus.lastErrorMessage
      ) {
        return state;
      }
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: nextStatus,
        },
      };
    }
    case "addAssistantMessage": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const message: ConversationItem = {
        id: `${Date.now()}-assistant`,
        kind: "message",
        role: "assistant",
        text: action.text,
      };
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems([...list, message]),
        },
      };
    }
    case "setThreadName": {
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      const next = list.map((thread) =>
        thread.id === action.threadId ? { ...thread, name: action.name } : thread,
      );
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: next,
        },
      };
    }
    case "setThreadTimestamp": {
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      if (!list.length) {
        return state;
      }
      let didChange = false;
      const next = list.map((thread) => {
        if (thread.id !== action.threadId) {
          return thread;
        }
        const current = thread.updatedAt ?? 0;
        if (current >= action.timestamp) {
          return thread;
        }
        didChange = true;
        return { ...thread, updatedAt: action.timestamp };
      });
      if (!didChange) {
        return state;
      }
      const sorted = prefersUpdatedSort(state, action.workspaceId)
        ? [
            ...next.filter((thread) => thread.id === action.threadId),
            ...next.filter((thread) => thread.id !== action.threadId),
          ]
        : next;
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: sorted,
        },
      };
    }
    case "appendAgentDelta": {
      const currentList = state.itemsByThread[action.threadId] ?? [];
      const runtimeMeta = resolveTurnMetaForMessage(
        state,
        action.threadId,
        action.turnId ?? null,
      );
      const index = currentList.findIndex((msg) => msg.id === action.itemId);
      let updatedItems: ConversationItem[];
      if (index >= 0 && currentList[index].kind === "message") {
        const existing = currentList[index];
        const existingMessage = applyAssistantRuntimeMeta(existing, runtimeMeta, action.turnId);
        const mergedText = mergeStreamingText(existing.text, action.delta);
        if (
          mergedText === existing.text &&
          existingMessage.model === existing.model &&
          existingMessage.contextWindow === existing.contextWindow &&
          existingMessage.turnId === existing.turnId
        ) {
          return state;
        }
        const next = [...currentList];
        next[index] = {
          ...existingMessage,
          text: mergedText,
        };
        updatedItems = prepareThreadItemsIncremental(next, index);
      } else {
        const baseMessage: Extract<ConversationItem, { kind: "message" }> = {
          id: action.itemId,
          kind: "message",
          role: "assistant",
          text: action.delta,
        };
        const next = [
          ...currentList,
          applyAssistantRuntimeMeta(baseMessage, runtimeMeta, action.turnId),
        ];
        updatedItems = prepareThreadItemsIncremental(next, next.length - 1);
      }
      const nextThreadsByWorkspace = maybeRenameThreadFromAgent({
        workspaceId: action.workspaceId,
        threadId: action.threadId,
        items: updatedItems,
        itemId: action.itemId,
        hasCustomName: action.hasCustomName,
        threadsByWorkspace: state.threadsByWorkspace,
      });
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
      };
    }
    case "completeAgentMessage": {
      const currentList = state.itemsByThread[action.threadId] ?? [];
      const runtimeMeta = resolveTurnMetaForMessage(
        state,
        action.threadId,
        action.turnId ?? null,
      );
      const index = currentList.findIndex((msg) => msg.id === action.itemId);
      let updatedItems: ConversationItem[];
      if (index >= 0 && currentList[index].kind === "message") {
        const existing = currentList[index];
        const existingMessage = applyAssistantRuntimeMeta(existing, runtimeMeta, action.turnId);
        const incomingText = action.text ?? "";
        const existingText = existing.text ?? "";
        const nextText =
          incomingText.length >= existingText.length ? incomingText : existingText;
        if (
          nextText === existing.text &&
          existingMessage.model === existing.model &&
          existingMessage.contextWindow === existing.contextWindow &&
          existingMessage.turnId === existing.turnId
        ) {
          return state;
        }
        const next = [...currentList];
        next[index] = {
          ...existingMessage,
          text: nextText,
        };
        updatedItems = prepareThreadItemsIncremental(next, index);
      } else {
        const baseMessage: Extract<ConversationItem, { kind: "message" }> = {
          id: action.itemId,
          kind: "message",
          role: "assistant",
          text: action.text,
        };
        const next = [
          ...currentList,
          applyAssistantRuntimeMeta(baseMessage, runtimeMeta, action.turnId),
        ];
        updatedItems = prepareThreadItemsIncremental(next, next.length - 1);
      }
      const nextThreadsByWorkspace = maybeRenameThreadFromAgent({
        workspaceId: action.workspaceId,
        threadId: action.threadId,
        items: updatedItems,
        itemId: action.itemId,
        hasCustomName: action.hasCustomName,
        threadsByWorkspace: state.threadsByWorkspace,
      });
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
      };
    }
    case "upsertItem": {
      let list = state.itemsByThread[action.threadId] ?? [];
      const item = normalizeItem(action.item);
      const isUserMessage = item.kind === "message" && item.role === "user";
      const hadUserMessage = isUserMessage
        ? list.some((entry) => entry.kind === "message" && entry.role === "user")
        : false;
      const renameText = isUserMessage ? extractRenameText(item.text) : "";
      if (
        item.kind === "review" &&
        item.state === "started" &&
        !item.id.startsWith("review-start-")
      ) {
        list = dropLatestLocalReviewStart(list);
      }
      if (item.kind === "review" && isDuplicateReviewById(list, item)) {
        return state;
      }
      if (item.kind === "review") {
        const existing = findMatchingReview(list, item);
        if (existing && existing.id !== item.id) {
          return state;
        }
      }
      const nextItem = ensureUniqueReviewId(list, item);
      const updatedItems = prepareThreadItems(upsertItem(list, nextItem));
      let nextThreadsByWorkspace = state.threadsByWorkspace;
      if (isUserMessage) {
        const threads = state.threadsByWorkspace[action.workspaceId] ?? [];
        const textValue = renameText;
        const updatedThreads = threads.map((thread) => {
          if (thread.id !== action.threadId) {
            return thread;
          }
          const looksAutoGenerated = looksAutoGeneratedThreadName(thread.name);
          const shouldRename =
            !hadUserMessage &&
            textValue.length > 0 &&
            looksAutoGenerated &&
            !action.hasCustomName;
          const nextName =
            shouldRename && textValue.length > 38
              ? `${textValue.slice(0, 38)}…`
              : shouldRename
                ? textValue
                : thread.name;
          return { ...thread, name: nextName };
        });
        const bumpedThreads =
          prefersUpdatedSort(state, action.workspaceId) && updatedThreads.length
            ? [
                ...updatedThreads.filter((thread) => thread.id === action.threadId),
                ...updatedThreads.filter((thread) => thread.id !== action.threadId),
              ]
            : updatedThreads;
        nextThreadsByWorkspace = {
          ...state.threadsByWorkspace,
          [action.workspaceId]: bumpedThreads,
        };
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
      };
    }
    case "setThreadItems":
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(action.items),
        },
      };
    case "setLastAgentMessage":
      if (
        state.lastAgentMessageByThread[action.threadId]?.timestamp >= action.timestamp
      ) {
        return state;
      }
      return {
        ...state,
        lastAgentMessageByThread: {
          ...state.lastAgentMessageByThread,
          [action.threadId]: { text: action.text, timestamp: action.timestamp },
        },
      };
    case "setLastAgentMessagesBulk": {
      if (action.updates.length === 0) {
        return state;
      }
      let didChange = false;
      const nextLastAgentMessageByThread = { ...state.lastAgentMessageByThread };
      action.updates.forEach((update) => {
        if (!update.threadId || !update.text) {
          return;
        }
        const existing = nextLastAgentMessageByThread[update.threadId];
        if (existing?.timestamp >= update.timestamp) {
          return;
        }
        nextLastAgentMessageByThread[update.threadId] = {
          text: update.text,
          timestamp: update.timestamp,
        };
        didChange = true;
      });
      if (!didChange) {
        return state;
      }
      return {
        ...state,
        lastAgentMessageByThread: nextLastAgentMessageByThread,
      };
    }
    case "appendReasoningSummary": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      const base =
        index >= 0 && list[index].kind === "reasoning"
          ? (list[index] as ConversationItem)
          : {
              id: action.itemId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const nextSummary = mergeStreamingText(
        "summary" in base ? base.summary : "",
        action.delta,
      );
      if (nextSummary === ("summary" in base ? base.summary : "")) {
        return state;
      }
      const updated: ConversationItem = {
        ...base,
        summary: nextSummary,
      } as ConversationItem;
      const next = index >= 0 ? [...list] : [...list, updated];
      const changedIndex = index >= 0 ? index : next.length - 1;
      if (index >= 0) {
        next[index] = updated;
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItemsIncremental(next, changedIndex),
        },
      };
    }
    case "appendReasoningSummaryBoundary": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      const base =
        index >= 0 && list[index].kind === "reasoning"
          ? (list[index] as ConversationItem)
          : {
              id: action.itemId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const nextSummary = addSummaryBoundary("summary" in base ? base.summary : "");
      if (nextSummary === ("summary" in base ? base.summary : "")) {
        return state;
      }
      const updated: ConversationItem = {
        ...base,
        summary: nextSummary,
      } as ConversationItem;
      const next = index >= 0 ? [...list] : [...list, updated];
      const changedIndex = index >= 0 ? index : next.length - 1;
      if (index >= 0) {
        next[index] = updated;
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItemsIncremental(next, changedIndex),
        },
      };
    }
    case "appendReasoningContent": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      const base =
        index >= 0 && list[index].kind === "reasoning"
          ? (list[index] as ConversationItem)
          : {
              id: action.itemId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const nextContent = mergeStreamingText(
        "content" in base ? base.content : "",
        action.delta,
      );
      if (nextContent === ("content" in base ? base.content : "")) {
        return state;
      }
      const updated: ConversationItem = {
        ...base,
        content: nextContent,
      } as ConversationItem;
      const next = index >= 0 ? [...list] : [...list, updated];
      const changedIndex = index >= 0 ? index : next.length - 1;
      if (index >= 0) {
        next[index] = updated;
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItemsIncremental(next, changedIndex),
        },
      };
    }
    case "appendPlanDelta": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      const base =
        index >= 0 && list[index].kind === "tool"
          ? list[index]
          : {
              id: action.itemId,
              kind: "tool",
              toolType: "plan",
              title: "方案",
              detail: "",
              status: "in_progress",
              output: "",
            };
      const existingOutput =
        base.kind === "tool" ? (base.output ?? "") : "";
      const mergedOutput = mergeStreamingText(existingOutput, action.delta);
      if (mergedOutput === existingOutput && index >= 0) {
        return state;
      }
      const updated: ConversationItem = {
        ...(base as ConversationItem),
        kind: "tool",
        toolType: "plan",
        title: "方案",
        detail: "Generating plan...",
        status: "in_progress",
        output: mergedOutput,
      } as ConversationItem;
      const next = index >= 0 ? [...list] : [...list, updated];
      const changedIndex = index >= 0 ? index : next.length - 1;
      if (index >= 0) {
        next[index] = updated;
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItemsIncremental(next, changedIndex),
        },
      };
    }
    case "appendToolOutput": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      if (index < 0 || list[index].kind !== "tool") {
        return state;
      }
      const existing = list[index];
      const mergedOutput = mergeStreamingText(existing.output ?? "", action.delta);
      if (mergedOutput === (existing.output ?? "")) {
        return state;
      }
      const updated: ConversationItem = {
        ...existing,
        output: mergedOutput,
      } as ConversationItem;
      const next = [...list];
      next[index] = updated;
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItemsIncremental(next, index),
        },
      };
    }
    case "addApproval": {
      const exists = state.approvals.some(
        (item) =>
          item.request_id === action.approval.request_id &&
          item.workspace_id === action.approval.workspace_id,
      );
      if (exists) {
        return state;
      }
      return { ...state, approvals: [...state.approvals, action.approval] };
    }
    case "removeApproval":
      return {
        ...state,
        approvals: state.approvals.filter(
          (item) =>
            item.request_id !== action.requestId ||
            item.workspace_id !== action.workspaceId,
        ),
      };
    case "addUserInputRequest": {
      const exists = state.userInputRequests.some(
        (item) =>
          item.request_id === action.request.request_id &&
          item.workspace_id === action.request.workspace_id,
      );
      if (exists) {
        return state;
      }
      return {
        ...state,
        userInputRequests: [...state.userInputRequests, action.request],
      };
    }
    case "removeUserInputRequest":
      return {
        ...state,
        userInputRequests: state.userInputRequests.filter(
          (item) =>
            item.request_id !== action.requestId ||
            item.workspace_id !== action.workspaceId,
        ),
      };
    case "setThreads": {
      const hidden = state.hiddenThreadIdsByWorkspace[action.workspaceId] ?? {};
      const visibleThreads = action.threads.filter((thread) => !hidden[thread.id]);
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: visibleThreads,
        },
        threadSortKeyByWorkspace: {
          ...state.threadSortKeyByWorkspace,
          [action.workspaceId]: action.sortKey,
        },
      };
    }
    case "setThreadListLoading":
      return {
        ...state,
        threadListLoadingByWorkspace: {
          ...state.threadListLoadingByWorkspace,
          [action.workspaceId]: action.isLoading,
        },
      };
    case "setThreadResumeLoading":
      return {
        ...state,
        threadResumeLoadingById: {
          ...state.threadResumeLoadingById,
          [action.threadId]: action.isLoading,
        },
      };
    case "setThreadListPaging":
      return {
        ...state,
        threadListPagingByWorkspace: {
          ...state.threadListPagingByWorkspace,
          [action.workspaceId]: action.isLoading,
        },
      };
    case "setThreadListCursor":
      return {
        ...state,
        threadListCursorByWorkspace: {
          ...state.threadListCursorByWorkspace,
          [action.workspaceId]: action.cursor,
        },
      };
    case "setThreadTokenUsage":
      return {
        ...state,
        tokenUsageByThread: {
          ...state.tokenUsageByThread,
          [action.threadId]: action.tokenUsage,
        },
      };
    case "setThreadTurnMeta": {
      const normalizedTurnId = normalizeNonEmptyString(action.turnId);
      if (!normalizedTurnId) {
        return state;
      }
      const normalizedModel = normalizeNonEmptyString(action.model);
      const previousForThread = state.turnMetaByThread[action.threadId] ?? null;
      const nextForThread: ThreadTurnRuntimeMeta = {
        threadId: action.threadId,
        turnId: normalizedTurnId,
        model: normalizedModel,
        contextWindow: previousForThread?.turnId === normalizedTurnId
          ? normalizeContextWindow(previousForThread.contextWindow)
          : null,
      };
      const nextTurnMetaByTurnId = { ...state.turnMetaByTurnId };
      if (
        previousForThread &&
        previousForThread.turnId !== normalizedTurnId &&
        nextTurnMetaByTurnId[previousForThread.turnId]?.threadId === action.threadId
      ) {
        delete nextTurnMetaByTurnId[previousForThread.turnId];
      }
      nextTurnMetaByTurnId[normalizedTurnId] = nextForThread;
      const currentItems = state.itemsByThread[action.threadId] ?? [];
      const nextItems = updateAssistantModelForTurn(
        currentItems,
        normalizedTurnId,
        normalizedModel,
      );
      return {
        ...state,
        itemsByThread:
          nextItems === currentItems
            ? state.itemsByThread
            : {
                ...state.itemsByThread,
                [action.threadId]: prepareThreadItems(nextItems),
              },
        turnMetaByThread: {
          ...state.turnMetaByThread,
          [action.threadId]: nextForThread,
        },
        turnMetaByTurnId: nextTurnMetaByTurnId,
      };
    }
    case "setThreadTurnContextWindow": {
      const normalizedTurnId = normalizeNonEmptyString(action.turnId);
      if (!normalizedTurnId) {
        return state;
      }
      const previousByTurn = state.turnMetaByTurnId[normalizedTurnId] ?? null;
      const previousByThread = state.turnMetaByThread[action.threadId] ?? null;
      const contextWindow = normalizeContextWindow(action.contextWindow);
      const nextMeta: ThreadTurnRuntimeMeta = {
        threadId: action.threadId,
        turnId: normalizedTurnId,
        model: normalizeNonEmptyString(previousByTurn?.model ?? previousByThread?.model) ?? null,
        contextWindow,
      };
      const currentItems = state.itemsByThread[action.threadId] ?? [];
      const nextItems = updateAssistantContextWindowForTurn(
        currentItems,
        normalizedTurnId,
        contextWindow,
      );
      return {
        ...state,
        itemsByThread:
          nextItems === currentItems
            ? state.itemsByThread
            : {
                ...state.itemsByThread,
                [action.threadId]: prepareThreadItems(nextItems),
              },
        turnMetaByThread: {
          ...state.turnMetaByThread,
          [action.threadId]: nextMeta,
        },
        turnMetaByTurnId: {
          ...state.turnMetaByTurnId,
          [normalizedTurnId]: nextMeta,
        },
      };
    }
    case "setRateLimits":
      return {
        ...state,
        rateLimitsByWorkspace: {
          ...state.rateLimitsByWorkspace,
          [action.workspaceId]: action.rateLimits,
        },
      };
    case "setAccountInfo":
      return {
        ...state,
        accountByWorkspace: {
          ...state.accountByWorkspace,
          [action.workspaceId]: action.account,
        },
      };
    case "setThreadTurnDiff":
      return {
        ...state,
        turnDiffByThread: {
          ...state.turnDiffByThread,
          [action.threadId]: action.diff,
        },
      };
    case "setThreadPlan":
      return {
        ...state,
        planByThread: {
          ...state.planByThread,
          [action.threadId]: action.plan,
        },
      };
    case "clearThreadPlan":
      return {
        ...state,
        planByThread: {
          ...state.planByThread,
          [action.threadId]: null,
        },
      };
    default:
      return state;
=======
const threadSliceReducers: ThreadSliceReducer[] = [
  reduceThreadLifecycle,
  reduceThreadConfig,
  reduceThreadItems,
  reduceThreadQueue,
  reduceThreadSnapshots,
];

export function threadReducer(state: ThreadState, action: ThreadAction): ThreadState {
  for (const reduceSlice of threadSliceReducers) {
    const nextState = reduceSlice(state, action);
    if (nextState !== state) {
      return nextState;
    }
>>>>>>> origin/main
  }
}
